"""ad category column added

Revision ID: 948ab41966c7
Revises: a045f0b87fe2
Create Date: 2019-08-02 17:12:36.370503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '948ab41966c7'
down_revision = 'a045f0b87fe2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('category', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad', 'category')
    # ### end Alembic commands ###
