"""add language to ads

Revision ID: c8cbbb5879e1
Revises: 09bf52fe54b5
Create Date: 2019-10-08 14:52:32.615405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8cbbb5879e1'
down_revision = '09bf52fe54b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ad', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ad', 'language')
    # ### end Alembic commands ###
